package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"os"
)

type kind struct {
	Name string `json:"name"`
	Code int    `json:"code"`
}

type schema struct {
	Kinds []kind `json:"kinds"`
}

func main() {
	input := flag.String("input", "", "input schema path")
	output := flag.String("output", "", "output go file")
	pkg := flag.String("pkg", "", "package hint from env expansion")
	flag.Parse()
	if *input == "" || *output == "" {
		fmt.Fprintln(os.Stderr, "missing input or output")
		os.Exit(1)
	}
	_ = *pkg
	data, err := os.ReadFile(*input)
	if err != nil {
		fmt.Fprintf(os.Stderr, "read: %v\n", err)
		os.Exit(1)
	}
	var s schema
	if err := json.Unmarshal(data, &s); err != nil {
		fmt.Fprintf(os.Stderr, "json: %v\n", err)
		os.Exit(1)
	}
	f, err := os.Create(*output)
	if err != nil {
		fmt.Fprintf(os.Stderr, "create: %v\n", err)
		os.Exit(1)
	}
	defer f.Close()
	fmt.Fprintln(f, "// Code generated by geninventory; DO NOT EDIT.")
	fmt.Fprintln(f, "")
	fmt.Fprintln(f, "package generated")
	fmt.Fprintln(f, "")
	for _, k := range s.Kinds {
		fmt.Fprintf(f, "// %sKind is the generated constant for %s.\n", k.Name, k.Name)
		fmt.Fprintf(f, "const %sKind = %d\n", k.Name, k.Code)
	}
	fmt.Fprintln(f, "")
	fmt.Fprintln(f, "// InventoryKind enumerates known kinds.")
	fmt.Fprintln(f, "type InventoryKind int")
	fmt.Fprintln(f, "")
	fmt.Fprintln(f, "const (")
	for _, k := range s.Kinds {
		fmt.Fprintf(f, "\tKind%s InventoryKind = %d\n", k.Name, k.Code)
	}
	fmt.Fprintln(f, ")")
}
