package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

const generatorVersion = "schemagen/v1"

type schemaDocument struct {
	Title      string                    `json:"title"`
	Properties map[string]schemaProperty `json:"properties"`
}

type schemaProperty struct {
	Type string `json:"type"`
}

func main() {
	schemaPath := flag.String("schema", "", "source schema path")
	outPath := flag.String("out", "", "generated Go path")
	flag.Parse()
	if *schemaPath == "" || *outPath == "" {
		fail("-schema and -out are required")
	}

	document, err := readSchema(*schemaPath)
	if err != nil {
		fail("read schema: %v", err)
	}
	if document.Title != "Forecast" || document.Properties["name"].Type != "string" || document.Properties["degree"].Type != "integer" {
		fail("unsupported schema shape")
	}

	if err := os.WriteFile(*outPath, []byte(render(*schemaPath, document)), 0o644); err != nil {
		fail("write generated file: %v", err)
	}
}

func readSchema(path string) (schemaDocument, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return schemaDocument{}, err
	}
	var document schemaDocument
	if err := json.Unmarshal(data, &document); err != nil {
		return schemaDocument{}, err
	}
	return document, nil
}

func render(schemaPath string, document schemaDocument) string {
	keys := make([]string, 0, len(document.Properties))
	for key := range document.Properties {
		keys = append(keys, key)
	}
	sort.Strings(keys)

	var output strings.Builder
	fmt.Fprintf(&output, "// Code generated by %s from %s; DO NOT EDIT.\n\n", generatorVersion, filepath.ToSlash(schemaPath))
	output.WriteString("package forecastschema\n\nimport \"reflect\"\n\n")
	output.WriteString("const (\n\tGeneratorVersion = \"schemagen/v1\"\n")
	fmt.Fprintf(&output, "\tSourceSchema     = %q\n)\n\n", filepath.ToSlash(schemaPath))
	output.WriteString("// Forecast is the checked-in binding for the source schema.\n")
	output.WriteString("type Forecast struct {\n")
	for _, key := range keys {
		goName := goName(key)
		goType := "string"
		if document.Properties[key].Type == "integer" {
			goType = "int"
		}
		fmt.Fprintf(&output, "\t%-6s %-6s `json:\"%s\"`\n", goName, goType, key)
	}
	output.WriteString("}\n\n")
	output.WriteString("// FieldDescriptor records the generated field registry.\n")
	output.WriteString("type FieldDescriptor struct {\n\tGoName string\n\tJSONName string\n\tKind reflect.Kind\n}\n\n")
	output.WriteString("// Descriptors is the generated descriptor registry.\nvar Descriptors = map[string]FieldDescriptor{\n")
	for _, key := range keys {
		kind := "reflect.String"
		if document.Properties[key].Type == "integer" {
			kind = "reflect.Int"
		}
		fmt.Fprintf(&output, "\t%q: {GoName: %q, JSONName: %q, Kind: %s},\n", key, goName(key), key, kind)
	}
	output.WriteString("}\n\n")
	output.WriteString("// NewForecast is the generated construction entry point.\nfunc NewForecast(name string, degree int) Forecast {\n\treturn Forecast{Degree: degree, Name: name}\n}\n\n")
	output.WriteString("// Reflect is the generated binding's reflective entry point.\nfunc Reflect(value Forecast, fieldName string) (any, bool) {\n\tfield := reflect.ValueOf(value).FieldByName(fieldName)\n\tif !field.IsValid() {\n\t\treturn nil, false\n\t}\n\treturn field.Interface(), true\n}\n")
	return output.String()
}

func goName(value string) string {
	if value == "" {
		return value
	}
	return strings.ToUpper(value[:1]) + value[1:]
}

func fail(format string, args ...any) {
	fmt.Fprintf(os.Stderr, format+"\n", args...)
	os.Exit(1)
}
