package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"os"
)

type entry struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type schema struct {
	Entries []entry `json:"entries"`
}

func main() {
	input := flag.String("input", "", "input schema path")
	output := flag.String("output", "", "output go file")
	flag.Parse()
	if *input == "" || *output == "" {
		fmt.Fprintln(os.Stderr, "missing input or output")
		os.Exit(1)
	}
	data, err := os.ReadFile(*input)
	if err != nil {
		fmt.Fprintf(os.Stderr, "read: %v\n", err)
		os.Exit(1)
	}
	var s schema
	if err := json.Unmarshal(data, &s); err != nil {
		fmt.Fprintf(os.Stderr, "json: %v\n", err)
		os.Exit(1)
	}
	f, err := os.Create(*output)
	if err != nil {
		fmt.Fprintf(os.Stderr, "create: %v\n", err)
		os.Exit(1)
	}
	defer f.Close()
	fmt.Fprintln(f, "// Code generated by geninfo; DO NOT EDIT.")
	fmt.Fprintln(f, "")
	fmt.Fprintln(f, "package generated")
	fmt.Fprintln(f, "")
	fmt.Fprintln(f, "// Info stores generated entries.")
	fmt.Fprintln(f, "type Info struct {")
	fmt.Fprintln(f, "\tKey string")
	fmt.Fprintln(f, "\tValue string")
	fmt.Fprintln(f, "}")
	fmt.Fprintln(f, "")
	fmt.Fprintln(f, "// InfoMap is the generated lookup table.")
	fmt.Fprintln(f, "var InfoMap = map[string]string{")
	for _, e := range s.Entries {
		fmt.Fprintf(f, "\t%q: %q,\n", e.Key, e.Value)
	}
	fmt.Fprintln(f, "}")
}
