// Code generated by schemagen/v1 from schema/forecast.json; DO NOT EDIT.

package forecastschema

import "reflect"

const (
	GeneratorVersion = "schemagen/v1"
	SourceSchema     = "schema/forecast.json"
)

// Forecast is the checked-in binding for the source schema.
type Forecast struct {
	Degree int    `json:"degree"`
	Name   string `json:"name"`
}

// FieldDescriptor records the generated field registry.
type FieldDescriptor struct {
	GoName   string
	JSONName string
	Kind     reflect.Kind
}

// Descriptors is the generated descriptor registry.
var Descriptors = map[string]FieldDescriptor{
	"degree": {GoName: "Degree", JSONName: "degree", Kind: reflect.Int},
	"name":   {GoName: "Name", JSONName: "name", Kind: reflect.String},
}

// NewForecast is the generated construction entry point.
func NewForecast(name string, degree int) Forecast {
	return Forecast{Degree: degree, Name: name}
}

// Reflect is the generated binding's reflective entry point.
func Reflect(value Forecast, fieldName string) (any, bool) {
	field := reflect.ValueOf(value).FieldByName(fieldName)
	if !field.IsValid() {
		return nil, false
	}
	return field.Interface(), true
}
